image:
  file: .gitpod.Dockerfile
tasks:
  # direnv will be reloaded and build the local flake to the nix store
  - before: >
      cabal build &&
      nix-store --export $(nix-store -qR gitpod-flake-ghc9) > .nix-store
  # We load the prebuilt .nix-store serialisation
  - init: >
      # We create a .nix-store serialisation so that it's prebuilt
      nix-store --import < .nix-store

    command: >
      cabal test

vscode:
  extensions:
    - bbenoist.Nix
    - rust-lang.rust
    - haskell.haskell
    - mkhl.direnv
