image:
  file: .gitpod.Dockerfile
tasks:
  # echo 'experimental-features = nix-command flakes' >> /home/gitpod/.config/nix/nix.conf
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      direnv allow
    command: >
      cabal test

vscode:
  extensions:
    - bbenoist.Nix
    - rust-lang.rust
    - haskell.haskell
    - mkhl.direnv
