image:
  file: .gitpod.Dockerfile

tasks:
  # direnv will be reloaded and will load the prebuilt .nix-store serialisation
  # if there is one, and then build the local flake to the nix store
  # we build the project (in the dist-newstyle workspace folder)
  # we copy the nix store into the .nix-store workspace folder for prebuilding
  - init: >
      cabal build &&
      nix copy --to .nix-store .#

  - command: >
      cabal test

vscode:
  extensions:
    - bbenoist.Nix
    - rust-lang.rust
    - haskell.haskell
    - mkhl.direnv
