name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # useful if you want to add emulation support with QEMU to be able to build against more platforms.
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # create and boot a builder using by default the docker-container builder driver. This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jmatsushita/gitpod-flake-ghc9:latest
